# Generated by Django 3.0.5 on 2021-10-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalariaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='ml_tools/static/ml_tools/images/malaria_uploads/', verbose_name='Malaria Image')),
            ],
        ),
        migrations.CreateModel(
            name='PneumoniaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='ml_tools/static/ml_tools/images/pneumonia_uploads/', verbose_name='Pneumonia Image')),
            ],
        ),
    ]
