# Generated by Django 3.0.5 on 2021-10-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MalariaImages',
            new_name='MalariaImage',
        ),
        migrations.RenameModel(
            old_name='PneumoniaImages',
            new_name='PneumoniaImage',
        ),
    ]
